### PR TITLE
addy.io 1.0.3

### LINKED ISSUE #239: Update to v1.x
### Description

Hi. Will this image need to be adapted to work with anonaddy 1.x + ?
Are there plans of doing so?

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #239 

* Rebranded to `addy.io` where it makes sense
* Update to 1.0.3
* PHP 8.2

### CODE REVIEW

**Comment by crazy-max** [comment]
@willbrowningme Should be good for review. About branding changes, I didn't touch the env vars to avoid breaking changes. Let me know if that sounds good.

**Review by willbrowningme — APPROVED** [review]
Changes look good to me!

**Comment by a-melon-007** [comment]
@crazy-max Any update on this?

**Comment by rehanone** [comment]
@crazy-max, is there any issue that is holing this PR? Kindly update as it has been more that a month sine the upstream release.

**Comment by anondev-sudo** [comment]
Is therw anything need to be changed or just pull the image and everything will work as before just with new ui?

**Pull request merged**
