### PR TITLE
Fix: emails forwarded even if alias is disabled

### PR DESCRIPTION
**Pull request by Koellewe**
This PR propagates an upstream (anonaddy/anonaddy) bugfix to this repo. 

- Upstream issue: anonaddy/anonaddy#72
- Issue on this repo: #121

### CODE REVIEW

**Comment by crazy-max** [comment]
Looks like there is a new issue with a dep wot linked to your changes: https://github.com/anonaddy/docker/runs/6039700411?check_suite_focus=true#step:7:1935

```
#31 19.13 Package manifest generated successfully.
#31 19.15 > @php artisan version:absorb --ansi
#31 19.56 
#31 19.57 In Git.php line 46:
#31 19.57                                                                                
#31 19.57   Unable to find git tags in this repository that matches the git.version.mat  
#31 19.57   cher pattern in version.yml                                                  
#31 19.57                                                                                
#31 19.57 
#31 19.59 Script @php artisan version:absorb --ansi handling the post-autoload-dump event returned with error code 1
```

Are you aware of this issue @willbrowningme?

**Comment by willbrowningme** [comment]
@crazy-max no I'm not aware of that issue, please could you try with the latest release [v0.11.2](https://github.com/anonaddy/anonaddy/releases/tag/v0.11.2).

**Comment by crazy-max** [comment]
> @crazy-max no I'm not aware of that issue, please could you try with the latest release [v0.11.2](https://github.com/anonaddy/anonaddy/releases/tag/v0.11.2).

@willbrowningme Fixed by #124.

@Koellewe Can you rebase with latest changes please?

**Comment by Koellewe** [comment]
@crazy-max done.

**Review by crazy-max — APPROVED** [review]
LGTM thanks

**Pull request merged**
