### PR TITLE
Simplify Dockerfile Alpine Linux apk usage

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Should made the Dockerfile a little bit tidier.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@crazy-max not sure if you can help take a look at this PR? Thanks.

**Comment by crazy-max** [comment]
@PeterDaveHello I think it's better to keep `--update` to get the latest list of available packages.

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello I think it's better to keep `--update` to get the latest list of available packages.

`--no-cache` will make sure that 😊

**Comment by crazy-max** [comment]
Yes indeed. Needs to rebase though.

**Comment by PeterDaveHello** [comment]
@crazy-max it's done 🙆‍♂️

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
